version: '3'

services:
  gormigrate:
    build:
      context: .
    depends_on:
      - postgres
      - mysql
      - sqlserver
    environment:
      POSTGRES_DSN: host=postgres user=gormigrate password=gormigrate dbname=gormigrate port=5432 sslmode=disable
      MYSQL_DSN: gormigrate:gormigrate@tcp(mysql:3306)/gormigrate?charset=utf8
      SQLSERVER_DSN: sqlserver://sa:LoremIpsum86@sqlserver:1433?database=master&encrypt=disable

  postgres:
    image: postgres:14-alpine
    environment:
      POSTGRES_DB: gormigrate
      POSTGRES_USER: gormigrate
      POSTGRES_PASSWORD: gormigrate

  mysql:
    image: mariadb:10
    environment:
      MYSQL_DATABASE: gormigrate
      MYSQL_ROOT_PASSWORD: gormigrate
      MYSQL_USER: gormigrate
      MYSQL_PASSWORD: gormigrate

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: Y
      MSSQL_SA_PASSWORD: LoremIpsum86
