# https://taskfile.dev

version: '3'

tasks:
  lint:
    desc: Runs golangci-lint
    cmds:
      - golangci-lint run

  test:
    cmds:
      - go test -v -tags {{.DATABASE}}

  test-mysql:
    desc: Run tests for MySQL
    cmds:
      - task: test
        vars: {DATABASE: mysql}

  test-postgres:
    desc: Run tests for PostgreSQL
    cmds:
      - task: test
        vars: {DATABASE: postgres}

  test-sqlite:
    desc: Run tests for SQLite
    cmds:
      - task: test
        vars: {DATABASE: sqlite}

  test-sqlserver:
    desc: Run tests for Microsoft SQL Server
    cmds:
      - task: test
        vars: {DATABASE: sqlserver}

  test-all:
    desc: Run tests for all databases
    deps: [test-mysql, test-postgres, test-sqlite, test-sqlserver]

# Docker tasks

  docker:compose:down:
    cmds:
      - docker compose down --volumes --remove-orphans

  docker:compose:up:
    desc: Start docker compose with database services
    deps: [docker:compose:down]
    cmds:
      - docker compose up --detach --no-deps --remove-orphans --force-recreate --no-deps gormigrate

  docker:compose:logs:
    desc: Start streaming docker compose logs
    cmds:
      - docker compose logs --follow --tail 50

  docker:build:
    cmds:
      - docker compose build gormigrate

  docker:test:
    deps: [docker:compose:up, docker:build]
    cmds:
      - defer: task docker:compose:down
      - docker compose run gormigrate go test -v -tags 'postgres sqlite mysql sqlserver'
